var dataset = [60, 40, 60, 80, 90, 120, 100, 120, 140, 160, 140, 180, 200, 220, 200, 240, 220, 200, 180, 140, 160, 120, 100, 80, 90, 110, 80, 60, 60]

d3.select("#myGraph")
	.selectAll("svg")
	.data(dataset)
	.enter()
    .append("rect")              
	.attr("style", "stroke:white")
	.attr("x", function(d, i) {return ((i * 30)+30)})
	.attr("y", 100)
	.attr("height", 0)
	.attr("width", 30)
	.transition()
	.duration(100)
	.style("fill", "skyblue")
	.transition()
	.duration(1200)
	.attr("height", function(d, i) {return d})
	.transition()
	.duration(800)
	.attr("height", function(d, i) {return (d-Math.random()*100)})
	.transition()
	.duration(900)
	.attr("height", function(d, i) {return (d+Math.random()*100)})
	.transition()
	.duration(1200)
	.attr("height", function(d, i) {return d})
	.transition()
	.duration(800)
	.attr("height", function(d, i) {return (d-Math.random()*100)})
	.transition()
	.duration(100)
	.style("fill", "purple")
	.transition()
	.duration(900)
	.attr("height", function(d, i) {return (d+Math.random()*100)})
	.transition()
	.duration(800)
	.attr("height", function(d, i) {return (d-Math.random()*100)})
	.transition()
	.duration(900)
	.attr("height", function(d, i) {return (d+Math.random()*100)})
	.transition()
	.duration(800)
	.attr("height", function(d, i) {return (d-Math.random()*100)})
	.transition()
	.duration(900)
	.attr("height", function(d, i) {return (d+Math.random()*100)})
	.transition()
	.duration(800)
	.attr("height", function(d, i) {return (d-Math.random()*100)})
	.transition()
	.duration(100)
	.style("fill", "orange")
	.transition()
	.duration(900)
	.attr("height", function(d, i) {return (d+Math.random()*100)})
	.transition()
	.duration(800)
	.attr("height", function(d, i) {return (d-Math.random()*100)})
	.transition()
	.duration(900)
	.attr("height", function(d, i) {return (d+Math.random()*100)})
	.transition()
	.duration(800)
	.attr("height", function(d, i) {return (d-Math.random()*100)})
	.transition()
	.duration(900)
	.attr("height", function(d, i) {return (d+Math.random()*100)})
	.transition()
	.duration(800)
	.attr("height", function(d, i) {return (d-Math.random()*100)})
	.transition()
	.duration(900)
	.attr("height", function(d, i) {return (d+Math.random()*100)})
	
 
	