//HONG NAHI 2015-20247//

d3.select("#color")
    .append("svg")
    .append("rect")
    .attr("style", "fill:yellow; stroke:none")
    .attr("x", 5)
    .attr("y", 5)
    .attr("width", 10)
    .attr("height", 10)
    .transition()
    .duration(1000)
    .attr("height", 140.5)
    .attr("width", 81.5)

d3.select("#color")
    .append("svg")
    .append("rect")
    .attr("style", "fill:blue; stroke:none")
    .attr("x", 92.5)
    .attr("y", 550)
    .attr("width", 10)
    .attr("height", 17)
    .transition()
    .duration(500)
    .attr("width", 54.4)
    .attr("height", 17)

d3.select("#color")
    .append("svg")
    .append("rect")
    .attr("style", "fill:blue; stroke:none")
    .attr("x", 152.5)
    .attr("y", 550)
    .attr("width", 10)
    .attr("height", 17)
    .transition()
    .duration(500)
    .attr("width", 36.5)
    .attr("height", 17)

d3.select("#color")
    .append("svg")
    .append("rect")
    .attr("style", "fill:blue; stroke:none")
    .attr("x", 195)
    .attr("y", 550)
    .attr("width", 10)
    .attr("height", 17)
    .transition()
    .duration(500)
    .attr("width", 24)
    .attr("height", 17)

d3.select("#color")
    .append("svg")
    .append("rect")
    .attr("style", "fill:red; stroke:none")
    .attr("x", 368)
    .attr("y", 435)
    .attr("width", 126)
    .attr("height", 10)
    .transition()
    .duration(2000)
    .attr("width", 126)
    .attr("height", 99)

d3.select("#color")
    .append("svg")
    .append("rect")
    .attr("style", "fill:red; stroke:none")
    .attr("x", 585)
    .attr("y", 540)
    .attr("width", 10)
    .attr("height", 10)
    .transition()
    .duration(1000)
    .attr("width", 21)
    .attr("height", 20)