d3.select("#colors")
	.append("svg")
	.append("rect")
	.attr("style", "fill:#FF4040; stroke-width:1; stroke:none")
	.attr("x", 90)
	.attr("y", 210)
	.attr("rx", 20)
	.attr("ry", 20)
	.attr("opacity", 0.7)
	.attr("width", 0)
	.attr("height", 0)
	.transition()
	.duration(2000)
	.attr("width", 45)
	.attr("height", 30)


d3.select("#colors")
	.append("svg")
	.append("rect")
	.attr("style", "fill:#FF4040; stroke-width:1; stroke:none")
	.attr("x", 270)
	.attr("y", 210)
	.attr("rx", 20)
	.attr("ry", 20)
	.attr("opacity", 0.7)
	.attr("width", 0)
	.attr("height", 0)
	.transition()
	.duration(2000)
	.attr("width", 45)
	.attr("height", 30)
