d3.select("#myGraph")
	.append("svg")
	.append("rect")
	.attr("class", "bar")
	.attr("x", 1)
	.attr("y", 1)
	.attr("height", 5)
	.attr("width", 1)
	.transition()
	.duration(3000)
	.attr("width", 1000)