d3.select("#myGraph")
	.append("rect")
	.style("fill", "black")
	.style("stroke", "black")
	.attr("x", 10)
	.attr("y", 10)
	.attr("height", 50)
	.attr("width", 0)
	.transition()
	.duration(3000)
	.attr("width", 300)

d3.select("#myGraph")
	.append("rect")	
	.style("fill", "red")
	.style("stroke", "black")
	.attr("x", 10)
	.attr("y", 60)
	.attr("height", 50)
	.attr("width", 0)
	.transition()
	.duration(3000)
	.attr("width", 300)

d3.select("#myGraph")
	.append("rect")	
	.style("fill", "yellow")
	.style("stroke", "black")
	.attr("x", 10)
	.attr("y", 110)
	.attr("height", 50)
	.attr("width", 0)
	.transition()
	.duration(3000)
	.attr("width", 300)

d3.select("#myGraph1")
	.append("rect")	
	.style("fill", "green")
	.style("stroke", "black")
	.attr("x", 10)
	.attr("y", 10)
	.attr("height", 0)
    .transition()
	.duration(3000)
	.attr("height", 150)
	.attr("width", 100)

d3.select("#myGraph1")
	.append("rect")	
	.style("fill", "white")
	.style("stroke", "black")
	.attr("x", 110)
	.attr("y", 10)
	.attr("height", 0)
    .transition()
	.duration(3000)
	.attr("height", 150)
	.attr("width", 100)

d3.select("#myGraph1")
	.append("rect")	
	.style("fill", "red")
	.style("stroke", "black")
	.attr("x", 210)
	.attr("y", 10)
	.attr("height", 0)
    .transition()
	.duration(3000)
	.attr("height", 150)
	.attr("width", 100)