d3.select("#myDrawing")
	.append("svg")
	.append("circle")
	.attr("style", "fill:orange; stroke:red")
	.attr("cx", 150)
	.attr("cy", 200)
	.attr("r", 50)
	.transition()
	.duration(3000)
	.attr("cx", 150)
	.attr("cy", 50)