d3.select("#myGraph")
	.append("svg")
	.append("circle")
	.attr("style", "fill:black; stroke:black")
	.attr("cx", 50)
	.attr("cy", 50)
	.attr("r", 40)

d3.select("#myGraph")	
	.append("svg")
	.append("circle")
	.attr("style", "fill:black; stroke:black")
	.attr("cx", 150)
	.attr("cy", 50)
	.attr("r", 40)	

d3.select("#myGraph")	
	.append("svg")
	.append("circle")
	.attr("style", "fill:white; stroke:black")
	.attr("cx", 100)
	.attr("cy", 150)
	.attr("r", 80)

d3.select("#myGraph")	
	.append("svg")
	.append("ellipse")
	.attr("style", "fill:white; stroke:black")
	.attr("cx", 70)
	.attr("cy", 120)
	.attr("rx", 8)
	.attr("ry", 25)

d3.select("#myGraph")	
	.append("svg")
	.append("ellipse")
	.attr("style", "fill:white; stroke:black")
	.attr("cx", 100)
	.attr("cy", 120)
	.attr("rx", 8)
	.attr("ry", 25)

d3.select("#myGraph")	
	.append("svg")
	.append("ellipse")
	.attr("style", "fill:black; stroke:black")
	.attr("cx", 85)
	.attr("cy", 160)
	.attr("rx", 15)
	.attr("ry", 10)




